name: Close Pull Requests

on:
  pull_request_target:
    types: [opened]
    branches:
    - '**/*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Close Pull
      run: gh pr close --comment "$COMMENT"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMENT: >
            We do not accept PRs on this repository. Please file an issue at
            https://github.com/python/cpython requesting an update to the
            source packages in this repository.
